.Dd November 15, 2022
.Dt XORBLEDNAM 1
.Sh NAME
.Nm xorblednam
.Nd fractal generator
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl buddhabrot
.Op Fl julia
.Op Fl mandelbrot
.Op Fl burning_ship
.Sh DESCRIPTION
The
.Nm
utility lets you generate some fractals.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl buddhabrot
generate a buddhabrot fractal
.It Fl julia
generate a julia fractal
.It Fl mandelbrot
generate a mandelbrot fractal
.It Fl mandelbrot
generate a burning ship fractal
.El
.Sh SEE ALSO
.Xr png 5
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xorblednam/issues
