.Dd September 24, 2022
.Dt XORBLEDNAM 1
.Sh NAME
.Nm xorblednam
.Nd fractal generator
.Sh SYNOPSIS
.Nm
.Op Fl bhjmv
.Sh DESCRIPTION
The
.Nm
utility lets you generate some fractals.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl b
generate a buddhabrot fractal
.It Fl h
show usage
.It Fl j
generate a julia fractal
.It Fl m
generate a mandelbrot fractal
.It Fl v
display the program version
.El
.Sh SEE ALSO
.Xr png 5
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xorblednam/issues
